name: amv_ddm2_s3
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Hive database dependencies
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  path_provider: ^1.6.18

  # Svg dependency
  flutter_svg: ^0.17.0

  # Color picker
  flutter_colorpicker: ^0.3.4

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Hive database dependencies
  hive_generator: ^0.7.3
  build_runner: ^1.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
